### ISSUE TITLE
3D Box Design - first draft

### ISSUE THREAD

**Issue by mikelovic** [CollectiveOpenSourceHardware/LibreSolarBox#2]
@DhavalGambhava  can you add a first draft of the box dimensions so we can check if the battery cells @case06 already designed  (#1) fit into it. Thank you!

**Comment by DhavalGambhava** [comment]
@mikelovic 
I uploaded 3D CAD Model and i added battery cells as well. It's fit well. Please check it.
Thxs!

**Comment by DhavalGambhava** [comment]
@case06  Oliver, please upload your battery Box layout.

**Comment by DhavalGambhava** [comment]
Guys ! 
I uploaded new final version of solar box. Please look it, and free fill to suggestion and verification. 
Thxs.
